USE DATABASE CRYPTO_DEV;
USE SCHEMA RAW;
USE WAREHOUSE CRYPTO_WH;

CREATE OR REPLACE STAGE s3_crypto_stage
  STORAGE_INTEGRATION = S3_CRYPTO_RAW
  URL = 's3://{{ RAW_BUCKET }}/raw/'
  FILE_FORMAT = ff_json_ndjson
  COMMENT = 'Read-only stage over S3 raw landing zone';
