USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS s3_crypto_raw
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::{{ AWS_ACCOUNT_ID }}:role/snowflake-s3-access-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://{{ RAW_BUCKET }}/raw/')
  COMMENT = 'Read access to crypto-pipeline raw bucket';

GRANT USAGE ON INTEGRATION s3_crypto_raw TO ROLE SYSADMIN;
